name: Android APK Yaratish (CI/CD)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v4

      - name: Java JDK 17 o'rnatish
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Flutter SDK o'rnatish
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'

      - name: Mobile app papkasiga o'tish va APK yig'ish
        run: |
          if [ -d "mobile_app" ]; then
            cd mobile_app
          fi
          flutter pub get
          flutter build apk --release

      - name: Tayyor APK faylini yuklab olish uchun saqlash (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: agrostar-davomat-release-apk
          path: "**/build/app/outputs/flutter-apk/app-release.apk"
